## cartridge.properties for cartridge app_sotbella_headless
#Mon Aug 1 18:36:14 CEST 2025
demandware.cartridges.app_sotbella_headless.multipleLanguageStorefront=true
demandware.cartridges.app_sotbella_headless.id=app_sotbella_headless