## cartridge.properties for cartridge bm_csv_upload
#Fri Oct 14 17:26:32 CEST 2025
demandware.cartridges.bm_csv_upload.multipleLanguageStorefront=true
demandware.cartridges.bm_csv_upload.id=bm_csv_upload