## cartridge.properties for cartridge bm_return_exchange
#Wed Nov 31 11:11:28 CEST 2025
demandware.cartridges.bm_return_exchange.multipleLanguageStorefront=true
demandware.cartridges.bm_return_exchange.id=bm_return_exchange